googleapis/java-bigquery

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: parentjobid in listjobs

---

pom.xml
samples/README.md
samples/pom.xml
samples/src/main/java/com/example/bigquery/AuthSnippets.java
samples/src/main/java/com/example/bigquery/CreateDataset.java
samples/src/main/java/com/example/bigquery/DeleteDataset.java
samples/src/main/java/com/example/bigquery/ListDatasets.java
samples/src/main/java/com/example/bigquery/QuickstartSample.java
samples/src/main/java/com/example/bigquery/SimpleApp.java
samples/src/main/java/com/example/bigquery/UpdateDatasetAccess.java
samples/src/main/java/com/example/bigquery/UpdateDatasetDescription.java
samples/src/main/java/com/example/bigquery/UpdateDatasetExpiration.java
samples/src/test/java/com/example/bigquery/AuthSnippetsIT.java
samples/src/test/java/com/example/bigquery/CreateDatasetIT.java
samples/src/test/java/com/example/bigquery/DeleteDatasetIT.java
samples/src/test/java/com/example/bigquery/ListDatasetsIT.java
samples/src/test/java/com/example/bigquery/QuickstartSampleIT.java
samples/src/test/java/com/example/bigquery/SimpleAppIT.java
samples/src/test/java/com/example/bigquery/UpdateDatasetAccessIT.java
samples/src/test/java/com/example/bigquery/UpdateDatasetDescriptionIT.java
samples/src/test/java/com/example/bigquery/UpdateDatasetExpirationIT.java

feat: migrate BQ Java samples from java-docs-samples to client lib

---

.kokoro/build.sh
pom.xml

By default, we won't run sample tests except during CI integration tests. To run them, you can enable the `include-samples` Maven profile.
This should allow releases to function -- a deploy is skipped completely if the last module in the reactor is configured to skip deployment.

chore: only run samples module during integration tests

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldTest.java

Fix formatting issue introduced in #43 that was not caught in the build due to #42

chore: fix formatting issue

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableDataWriteChannelTest.java
pom.xml

All updates:
| Package | Update | Change |
|---|---|---|
| `com.google.auth:google-auth-library-oauth2-http` | minor | `0.18.0` -> `0.19.0` |
| `com.google.auto.value:auto-value` (jdk 1.8+) | minor | `1.6.6` -> `1.7` |
| `com.google.auto.value:auto-value-annotations` | minor | `1.6.6` -> `1.7` |
| [com.google.api:gax-bom](https://togithub.com/googleapis/gax-java) ([source](https://togithub.com/googleapis/gax-java)) | minor | `1.51.0` -> `1.52.0` |
| [com.google.api:gax-grpc](https://togithub.com/googleapis/gax-java) ([source](https://togithub.com/googleapis/gax-java)) | minor | `1.51.0` -> `1.52.0` |
| [com.google.cloud:google-cloud-core-grpc](https://togithub.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-core-grpc) | minor | `1.91.3` -> `1.92.0` |
| …

deps: update dependencies

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryOptionsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableDataWriteChannelTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelperTest.java

Fixes #69 
Also see https://engdoc.corp.google.com/eng/doc/devguide/java/testing/exceptions.md?cl=head

chore: remove deprecated method

---

samples/pom.xml
samples/src/main/java/com/example/bigquery/RelaxColumnMode.java
samples/src/test/java/com/example/bigquery/RelaxColumnModeIT.java

feat: new sample - Tables: Relax column

---

samples/src/main/java/com/example/bigquery/GetDatasetInfo.java
samples/src/test/java/com/example/bigquery/GetDatasetInfoIT.java

feat: sample - Get dataset properties

---

samples/src/main/java/com/example/bigquery/RunLegacyQuery.java
samples/src/test/java/com/example/bigquery/CopyMultipleTablesIT.java
samples/src/test/java/com/example/bigquery/RunLegacyQueryIT.java

feat: sample - run a legacy SQL query

---

samples/src/main/java/com/example/bigquery/LoadParquetReplaceTable.java
samples/src/test/java/com/example/bigquery/LoadParquetReplaceTableIT.java

feat: new sample - load: GCS parquet replace existing table

---

samples/src/main/java/com/example/bigquery/LoadParquet.java
samples/src/test/java/com/example/bigquery/LoadParquetIT.java

feat: sample - load parquet

---

samples/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
samples/src/test/java/com/example/bigquery/AddColumnLoadAppendIT.java
samples/src/test/java/com/example/bigquery/CreateDatasetIT.java
samples/src/test/java/com/example/bigquery/CreateTableIT.java

feat: sample - add col load append

---

google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableDefinition.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java

chore: add debug statement to StandardTableDefinition

---

google-cloud-bigquery/pom.xml

address build error: https://source.cloud.google.com/results/invocations/146b9fcc-cf53-41f1-a52e-e6ff1f857b2e/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigquery%2Fpresubmit%2Fdependencies/log
[WARNING] Used undeclared dependencies found:
[WARNING]    org.hamcrest:hamcrest:jar:2.2:test
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:2.2:test

deps: bump hamcrest dep version and artifactId

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java

fix: missing fields in tablefield

---

README.md

docs: broken links

---

samples/src/main/java/com/example/bigquery/LoadTableClustered.java
samples/src/test/java/com/example/bigquery/LoadTableClusteredIT.java

samples: load table clustered

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: allUsers access

---

pom.xml

This might help when users' build tools don't understand the Maven profiles configuration.

chore: move autovalue version properties from the JDK 1.8 profile into the base profile

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/HivePartitioningOptions.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/HivePartitioningOptionsTest.java

feat: expose hivepartitioningoptions

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add struct query parameters

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/HivePartitioningOptions.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java

feat: add support for Hive partitioning options when creating external tables

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueTest.java

fix: fieldvalue gettimestamp

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Field.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/PolicyTags.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SchemaTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Basic support for policy tags.
IT test doesn't actually use a valid policy, but the BQ backend does accept tags that match the expected pattern without the policy tag being defined in data catalog.  Related: internal issue 154544391

feature: add policy tags support (column ACLs)

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TimePartitioning.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java

fix: null type in timepartitioning.

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionProperty.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ConnectionPropertyTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support connection properties for job and query

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TimePartitioning.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimePartitioningTest.java

feat: add hourly partitioning support

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExtractJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add extract model for extractjobconfiguration

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/WriteChannelConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add labels for writechannelconfiguration

---

samples/snippets/src/main/java/com/example/bigquery/CreateClusteredTable.java
samples/snippets/src/test/java/com/example/bigquery/CreateClusteredTableIT.java

As of the current version we can see that the schema and clustering fields
is already defined in the functions, however by passing it as the arguments
engineer can easily change the schema and clustering fields in the IT test
thus enable them to understand more about the concept.
Fixes #380  ☕️

docs(samples): Include clustering fields and schema in CreateClusteredTable as part of the function arguments

---

samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java
samples/snippets/src/test/java/com/example/bigquery/LoadTableClusteredIT.java

As of the current version we can see that the schema and clustering fields
is already defined in the functions, however by passing it as the arguments
engineer can easily change the schema and clustering fields in the IT test
thus enable them to understand more about the concept.
Fixes #381 ☕️

docs(samples): Include clustering fields and schema in LoadTableClusteredIT as part of the function arguments

---

samples/snippets/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
samples/snippets/src/main/java/com/example/bigquery/LoadParquet.java
samples/snippets/src/main/java/com/example/bigquery/LoadParquetReplaceTable.java
samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java
samples/snippets/src/main/java/com/example/bigquery/UpdateDatasetAccess.java
samples/snippets/src/main/java/com/example/bigquery/UpdateDatasetExpiration.java
samples/snippets/src/main/java/com/example/bigquery/UpdateTableExpiration.java
samples/snippets/src/test/java/com/example/bigquery/AddColumnLoadAppendIT.java
samples/snippets/src/test/java/com/example/bigquery/LoadParquetIT.java
samples/snippets/src/test/java/com/example/bigquery/LoadParquetReplaceTableIT.java
samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsIT.java
samples/snippets/src/test/java/com/example/bigquery/UpdateDatasetAccessIT.java
samples/snippets/src/test/java/com/example/bigquery/UpdateDatasetExpirationIT.java
samples/snippets/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java

As the previous PR https://github.com/googleapis/java-bigquery/pull/382  and https://github.com/googleapis/java-bigquery/pull/379.
I find several other samples that have the tendencies of including tightly coupled 
variable for each of specific method. Hence I think it will be better to pass it as an argument instead of simply using local variable inside of the method.
Fixes #387  ☕️

docs(samples): Convert tightly coupled local variable inside of method into method arguments

---

samples/snippets/src/main/java/com/example/bigquery/CreatePartitionedTable.java
samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
samples/snippets/src/main/java/com/example/bigquery/LoadLocalFile.java
samples/snippets/src/test/java/com/example/bigquery/CreatePartitionedTableIT.java
samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
samples/snippets/src/test/java/com/example/bigquery/LoadLocalFileIT.java

As of the current version we can see that more options related to argument
are written inside of the test instead of included as arguments, so I think
as this is tightly coupled with argument, it will be better to pass it as well.
Fixes #394 ☕️

docs(samples): Convert tightly coupled local variable involved options inside of method into method arguments

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigtableOptionsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/PolicyTagsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryStageTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimePartitioningTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TimelineSampleTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ViewDefinitionTest.java

chore: cover code coverage

---

samples/snippets/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java

We found that UpdateTableExpirationIT is flaky since during table creation the table is not created.
Fixes #393 ☕️

docs(samples): Fix flaky test

---

samples/snippets/src/main/java/com/example/bigquery/ExtractTableToCsv.java
samples/snippets/src/test/java/com/example/bigquery/ExtractTableToCsvIT.java

docs(samples): rename extract table json to extract table csv

---

samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java

docs(samples): added extract to json and accompanying test

---

samples/install-without-bom/src/test/resources/userSessionsData.json
samples/snapshot/src/test/resources/userSessionsData.json
samples/snippets/src/main/java/com/example/bigquery/UpdateTableDML.java
samples/snippets/src/test/java/com/example/bigquery/UpdateTableDMLIT.java
samples/snippets/src/test/resources/userSessionsData.json

docs(samples): add update table using dml query sample

---

samples/snippets/src/main/java/com/example/bigquery/BrowseTable.java
samples/snippets/src/test/java/com/example/bigquery/BrowseTableIT.java

docs(samples): adding browse table sample and test

---

samples/snippets/src/main/java/com/example/bigquery/CreateRangePartitionedTable.java
samples/snippets/src/test/java/com/example/bigquery/CreateRangePartitionedTableIT.java

docs(samples): add create range partition table

---

samples/snippets/src/main/java/com/example/bigquery/CreateJob.java
samples/snippets/src/test/java/com/example/bigquery/CreateJobIT.java

docs(samples): add create job

---

samples/snippets/src/main/java/com/example/bigquery/InsertingDataTypes.java
samples/snippets/src/test/java/com/example/bigquery/InsertingDataTypesIT.java

docs(samples): add insert data types

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/AclTest.java
samples/snippets/src/test/java/com/example/bigquery/AddEmptyColumnIT.java

In Acl there's still untested class particularly the IamMember. Also we can still improve the coverage by improving test for Group.
Fixes #489 ☕️

test: Improve code coverage for Acl

---

samples/snippets/src/main/java/com/example/bigquery/CreateJob.java
samples/snippets/src/main/java/com/example/bigquery/GetJob.java
samples/snippets/src/test/java/com/example/bigquery/GetJobIT.java

docs(samples): add get job

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/PolicyTags.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/PolicyTagsTest.java

When you delete a policy tag from a column in BigQuery, rather than
eliding the policyTag message entirely, it will return an empty
message (with no names field).  This change treats such responses
as equivalent to no PolicyTag message being present.
reported as internal issue: 160857208

fix: handle malformed backend responses for PolicyTag messages

---

samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGcs.java

Correcting comment

---

samples/snippets/src/main/java/com/example/bigquery/DDLCreateView.java
samples/snippets/src/test/java/com/example/bigquery/DDLCreateViewIT.java

docs(samples): add create view ddl

---

samples/snippets/src/main/java/com/example/bigquery/TableInsertRowsWithoutRowIds.java
samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsWithoutRowIdsIT.java

docs(samples): add insert rows without rowids in a table

---

samples/snippets/src/main/java/com/example/bigquery/QueryWithPositionalTypesParameters.java
samples/snippets/src/test/java/com/example/bigquery/QueryWithPositionalTypesParametersIT.java

docs(samples): add query with positional type parameters

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: get recordvalue by field name

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: throw jobexception for invalid multiple statements query

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java

This change alters HTTP response behavior by eliding unnecessary
whitespace from JSON responses.

feat(bigquery): explicitly ask for dense responses from HTTP backend

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: use bigquery exception

---

samples/snippets/src/main/java/com/example/bigquery/UndeleteTable.java
samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java

docs(samples): fix flaky test case for undelete table

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java

test: use pages empty

---

.github/sync-repo-settings.yaml

Turns out, the GitHub API cannot handle the `maintain` and `triage` permissions quite yet for teams.  We can set those manually, or switch to `admin`/`write`.  I bumped `api-bigquery` up to `admin here, but I'm open for whatever.

build: remove maintainer permission from repo config

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
samples/snippets/src/main/java/com/example/bigquery/CreateClusteredTable.java
samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java

docs: update clustering field docstrings

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java

Add connecitonId to ExternalTableDefinition to allow external data source query through the BigQuery client.

feat: add connectionId support for external data sources

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: request id for fast query path

---

samples/install-without-bom/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml
samples/snippets/src/main/java/com/example/bigquery/QueryExternalBigtableTemp.java
samples/snippets/src/test/java/com/example/bigquery/QueryExternalBigtableTempIT.java

docs(samples): add query external bigtable using temp table

---

samples/snippets/src/main/java/com/example/bigquery/QueryExternalBigtablePerm.java
samples/snippets/src/test/java/com/example/bigquery/QueryExternalBigtablePermIT.java

docs(samples): add query external bigtable using permanent table

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryException.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: bigquery exception get reason and message

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: fix start index with page size for list rows

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/HivePartitioningOptions.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/HivePartitioningOptionsTest.java
pom.xml

feat: add requirePartitionFilter field in HivePartitioningOptions

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: schema and totalRows for duplicate request ids

---

google-cloud-bigquery/pom.xml

google-http-client will update before it can be updated in google-cloud-storage (which also has a dependency on google-http-client). By making this version first, we ensure that any transitive dependency versions will take precedence from google-http-client directly.

chore(deps): reorder dependencies so http-client is before storage

---

.kokoro/run_samples_resource_cleanup.sh

Nightly samples cleanup job failed due to below error:
```
Executing: docker run --rm --interactive --network=host --privileged --volume=/var/run/docker.sock:/var/run/docker.sock --workdir=/tmpfs/src --entrypoint=github/java-bigquery/.kokoro/run_samples_resource_cleanup.sh --env-file=/tmpfs/tmp/tmpccr95nk7/envfile --volume=/tmpfs:/tmpfs gcr.io/cloud-devrel-kokoro-resources/java8
standard_init_linux.go:190: exec user process caused "exec format error"
```
This PR is to fix the above.

ci: fix shell script "exec format error"

---

samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java

fix(samples): dataset getcreatetime

---

.kokoro/nightly/samples.cfg
.kokoro/run_samples_resource_cleanup.sh

Fixes `github/java-bigquery/.kokoro/run_samples_resource_cleanup.sh: line 32: /tmpfs/src/gfile/bigquery_secrets.txt: No such file or directory` seen in Fusion build logs: https://g3c.corp.google.com/results/invocations/55fae1ae-eb61-4308-90e6-c2b17d08ccd5/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigquery%2Fnightly%2Fsamples/log

ci: enable secrete manager for nightly resource cleanup

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DatasetInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/AclTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SerializationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: support authorized UDF entries in dataset ACL

---

.kokoro/run_samples_resource_cleanup.sh

Fixes ``` ERROR: (gcloud.auth.activate-service-account) Unable to read file [/tmpfs/src/gfile/service-acct.json]: [Errno 2] No such file or directory: '/tmpfs/src/gfile/service-acct.json' ```
Full trace: https://g3c.corp.google.com/results/invocations/a20c9009-fb3a-4f66-a6c1-11ad49a8db5b/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigquery%2Fnightly%2Fsamples/log

ci: prepend kokoro root directory to the path to service-acct.json

---

.kokoro/run_samples_resource_cleanup.sh

To run nightly samples resource cleanup jobs.
Still observing:
```
ERROR: (gcloud.auth.activate-service-account) Unable to read file [/tmpfs/src/gfile/service-acct.json]: [Errno 2] No such file or directory: '/tmpfs/src/gfile/service-acct.json'
```
https://g3c.corp.google.com/results/invocations/cc95e6ae-5986-430d-b69e-ef87696ba02c/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigquery%2Fnightly%2Fsamples/log

ci: update Kokoro root directory

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: nullpointerexception for listroutines and listmodels

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

When the query job takes more than 10s we must fall back to the old query path!
cc @epavan

fix: make sure to fall back to old query path when query job is incomplete

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java

- [ v] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [v ] Ensure the tests and linter pass
- [ v] Code coverage does not decrease (if any source code was changed)
- [ v] Appropriate docs were updated (if necessary)
Fixes #971

fix: update listPartitions() to support tables from other projects

---

google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryRequestInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

feat: set requestId for fast query path in QueryRequestInfo instead of QueryJobConfiguration

---

samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java

refactor(samples): query pagination

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This makes it possible to run the tests in a VPC Service Controls perimeter where public buckets may be unreachable.

chore: add env var for changing cloud-samples-data bucket

---

samples/snippets/src/main/java/com/example/bigquery/UpdateViewQuery.java

Passed updated view definition to bigquery.update() method.
Fixes #1051  ☕️

samples: Fixes #1051

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java

feat: add reservation usage in job statistics

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support for javascript UDFs determinism level

---

samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java

Based on feedback from a support case, I've made some changes to make this more clear and more accurate to what the comments indicate
Created #1207 to track this
Fixes #1207 ☕️

docs(samples): update querypagination sample

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Unblocks JDBC migration to the Java client library.

feat: add support for parameterMode in QueryJobConfiguration

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTableType.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardSQLTableTypeTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Allow BigQuery client library users to define table-valued functions (TVFs) that return table data.

feat: add support for user defined TVFs

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/MaterializedViewDefinition.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/MaterializedViewDefinitionTest.java

feat: add support for partitioning and clustering in MaterializedViewDefinition

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ParquetOptions.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ParquetOptionsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add ParquetOptions support and expose it in LoadJobConfiguration and ExternalTableDefinition classes

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Towards b/188414733
Implemented in LoadJobConfiguration and ExternalTableDefinition
cc @mingyuzhong

feat: add support for DecimalTargetTypes

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryBaseService.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java

Added retry logic on `java.net.ConnectException` and `java.net.UnknownHostException` for `BigQueryImpl.listDatasets()` and `BigQueryImpl.queryRpc()` methods
Fixes # https://github.com/googleapis/java-bigquery/issues/1254 and https://github.com/googleapis/gax-java/issues/1301 ☕️

fix: handle specific exceptions

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Dataset.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java

Fixed `Dataset.get(String tableId, TableOption... options)` method's implementation to use the projectId associated with DatasetId, if one is present. Otherwise default to Bigquery's instance's projectId. Added test case.  
Fixes #1369  ☕️

fix: bug fix for get method of Bigquery Dataset

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support for jobs.delete

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Field.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SchemaTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support for parameterized type

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DmlStats.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DmlStatsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Provides detailed statistics for DML statements Present only for DML statements INSERT, UPDATE, DELETE or TRUNCATE.
Towards b/186432630

feat: add dmlStatistics support

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryErrorMessages.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryConfig.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java

Updated `BigQueryRetryAlgorithm` so that it can retry on error messaged like:
```
{
"code" : 400,
"errors" : [ {
"domain" : "global",
"message" : "Job exceeded rate limits: Your table exceeded quota for table update operations. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas",
"reason" : "jobRateLimitExceeded"
} ],
"message" : "Job exceeded rate limits: Your table exceeded quota for table update operations. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas",
"status" : "INVALID_ARGUMENT"
}
```
The `BigQueryRetryAlgorithm.shouldRetryBasedOnBigQueryRetryConfig` logic will work as follows: 
1. Apply a case insensitive contains check on the error message to check if it should be retied
2. If  the contains check fails then …

feat: Updated `BigQueryRetryAlgorithm` so that it can retry on RateLimit Errors using RegEx

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support for transactioninfo in query statistics

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryHelper.java

to help customer further debug

fix: add retry logging for BigQueryRetryAlgorithm.java

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java

Fix for issue where `BigQueryImpl.testIamPermissions` will throw a NullPointerException if the caller does not have any of the permissions being checked.
Fixes #1595 ☕️

fix: do not throw NPE from BigQueryImpl.testIamPermissions

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/AvroOptions.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/AvroOptionsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java

New AvroOptions class and wired into ExternalTableDefinition

feat: add support for AvroOptions

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Towards #1644
Temp fix timestamp rounding error (to microsecond) which can be reproduced by setting query priority to `INTERACTIVE`.

fix: fix timestamp rounding issue

---

pom.xml

I found the pom.xml has a strange white space character in pom.xml.
Maybe Maven just ignores such white space characters but it's better to fix it.

fix: removing a new line character in a property

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BiEngineReason.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BiEngineStats.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support for BI Engine Statistics

---

google-cloud-bigquery/pom.xml
pom.xml

chore: import datacatalog BOM to avoid renovate-bot issues

---

google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTypeName.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

feat: add JSON type support

---

samples/snippets/src/main/java/com/example/bigquery/GrantViewAccess.java
samples/snippets/src/test/java/com/example/bigquery/GrantViewAccessIT.java

Fixes issue: https://github.com/googleapis/java-bigquery/issues/1806

docs(samples): fix GrantViewAccess sample IT failure

---

.github/.OwlBot.lock.yaml
.github/workflows/auto-release.yaml
google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTypeName.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

feat: add Interval type support

---

README.md
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
google-cloud-bigquery/src/test/resources/META-INF/native-image/reflect-config.json
google-cloud-bigquery/src/test/resources/META-INF/native-image/resource-config.json

This PR explicitly specifies the resource (in this case, `QueryTestData.csv`) that needs to be accessible at run-time through the use of the `resource-config.json` file. Using this json config file allows the resource to be accessible when [methods such as Class.getResource() and Class.getResourceAsStream() are used](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/Resources.md). However, referencing a resource using the full path still results in the `NoSuchFileException`. 
This PR also adds some additional reflection configuration to resolve the following issues:
```
Caused by: java.lang.IllegalArgumentException: field private java.util.List com.google.api.client.googleapis.json.GoogleJsonError.details …
```

fix(java): add additional configurations to fix native image tests

---

samples/snippets/src/main/java/com/example/bigquery/TableExists.java
samples/snippets/src/test/java/com/example/bigquery/TableExistsIT.java

Added `null` check in the sample and modified the test case to test for "Table not found"

docs(sample): Table exists sample fix

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Per discussion related to go/bq-external-table-schema

feat: set Table.Schema for permanent external tables

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

In accordance with https://github.com/googleapis/google-cloud-go/pull/5846

chore: make policy tag setup use unique display names

---

samples/native-image-sample/README.md
samples/native-image-sample/pom.xml

Adding setup instructions that were previously missing. Removing the native-image-support module which is no longer needed.

docs(sample): remove unused dependency and add setup instructions

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Fixes #1924
Per discussion in b/227623980

chore: IT clean-up

---

google-cloud-bigquery/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-bigquery/reflect-config.json
google-cloud-bigquery/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-bigquery/resource-config.json

Fixes  https://github.com/googleapis/java-bigquery/issues/2007. Reproducer: https://github.com/mpeddada1/native-image-arrow.
cc @meltsufin

fix(java): add native image configuration for Apache Arrow

---

.kokoro/build.sh
.kokoro/dependencies.sh
CHANGELOG.md
benchmark/pom.xml
benchmark/src/main/java/com.google.cloud.bigquery/ConnImplBenchmark.java
google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryDryRunResult.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryDryRunResultImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultSetImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultStats.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultStatsImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuerySQLException.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Connection.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionSettings.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ConnectionImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ConnectionSettingsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITNightlyBigQueryTest.java
pom.xml
samples/install-without-bom/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml
versions.txt

Background: [go/bq-sql-client-java](https://goto.google.com/bq-sql-client-java)
This PR provides a completely new Connection interface which defines separate APIs for different types of queries. This allows us to provide an industry standard way for database applications to build against the Java client library. We provide 3 new [JDBC-esque](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html) API methods:
**[In-scope for this PR] executeSelect - Only supports read only SELECT queries.**
[Not in this PR] executeUpdate - Only supports DML and DDL. 
[Not in this PR] execute - Any SQL - scripts, DML, DDL, SELECT etc statements.
We also integrate with the [BigQueryStorage client library](https://github.com/googleapis/java-bigquerystorage) and use the high throughput Read API …

feat: add Connection interface

---

google-cloud-bigquery/pom.xml
pom.xml

Relates to https://github.com/googleapis/java-bigquery/pull/1374
- Use google-cloud-bigquerystorage BOM to manage all the related dependency versions.
- Use dependencyManagement to manager version numbers

chore: restructure dependencies for the new features related to bigquerystorage Java client

---

pom.xml

so that we don't get multiple dependency update PRs for arrow-related dependencies

chore(deps): manage arrow version in the parent pom properties

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java

Added and wired `markEoS` and `markLast` method to avoid blocking of `next()` during interrupts
Added flag in `next()` which avoids blocking/timeout when `next()` is called after we have run our of records
Fixes #2033 ☕️

fix: fix for flaky connection close issue

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java

Added a `null` check for  `firstPage.getSchema()` as we might get null schema when the job is long running (We get schema using dryRun in such cases)
Fixes #2049 ☕️

fix: NPE issue with testMultipleRuns

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITNightlyBigQueryTest.java

Added and wired flagEndOfStream. Refactored and improved Thread interrupt logic.
Fixed the `testConnectionClose` testcase logic
Fixes #2039 ☕️

fix: Flaky connenction close issue

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

String comparison of values, eg `1.40845209522E9` vs `1408452095.22` seems to be failing, so comparing the values as epoc (Long) instead
Fixes #2056 ☕️

fix: Flaky testPositionalQueryParameters

---

README.md
renovate.json

to address issues like:
which occurs since shared-dependencies updates take different amount of time to roll out in various cloud clients.
[Full trace](https://github.com/googleapis/java-bigquery/runs/6578164174?check_suite_focus=true)
In this PR, we group the GCP Java client dependencies together so that their updates will be proposed in one single PR when they get updated:
```
"^com.google.cloud:google-cloud-datacatalog",
"^com.google.cloud:google-cloud-bigquerystorage-bom",
"^com.google.cloud:google-cloud-storage"
```
In addition, we classify `^com.google.cloud:google-cloud-bigtable` as a `chore` dependency update since it is only used in samples and it should not result in a client library version bump.

chore: manage dependency updates from renovate-bot

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CopyJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Add destinationExpirationTime to CopyJobConfiguration
Fixes #1929 ☕️

feat: add destinationExpirationTime to CopyJobConfiguration

---

google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryRequestInfoTest.java
pom.xml

Removed Assertj-core  and refactored related testcase
Fixes #2083☕️

fix: Assertj-core cleanup

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Disabling `testReadAPIIterationAndOrder` and `testReadAPIConnectionMultiClose` as there are failing with `com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed` and they are blocking pending PRs and releases.
These are using the newly release Beta `executeSelect` functionality and we can enable these when https://github.com/googleapis/gax-java/issues/1712 or b/235591056 are resolved

chore: Disabling testReadAPIIterationAndOrder and testReadAPIConnectionMulti

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR adds support for binding a geography value directly as a query parameter, without the indirection of converting a string type to a geography time in the query body.
Related internal issue: b/238336732

feat(bigquery): enable use of GEOGRAPHY query params

---

README.md
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml
samples/snippets/src/test/java/com/example/bigquery/UpdateModelDescriptionIT.java

deps: update dependency org.threeten:threeten-extra to v1.7.1
deps: update dependency com.google.cloud:google-cloud-storage to 2.11.0
deps: update dependency com.google.cloud:google-cloud-datacatalog-bom to 1.9.1
deps: update dependency com.google.cloud:google-cloud-bigquerystorage-bom to 2.18.0
build(deps): update dependency com.google.cloud:google-cloud-shared-config to v1.5.3
deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v3

deps: update dependency com.google.apis:google-api-services-bigquery to v2-rev20220716-2.0.0

---

README.md
samples/snippets/src/main/java/com/example/bigquery/AuthorizeDataset.java
samples/snippets/src/test/java/com/example/bigquery/AuthorizeDatasetIT.java

Fixes#2188
Fixed the logic for authorizing a bigquery user dataset but updating the source dataset acl with that of the user dataset information.

samples / fixing authorize dataset logic by updating source dataset acl 

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CsvOptions.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CsvOptionsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

https://groups.google.com/g/google-cloud-sdk-announce/c/Wf6jcd-_Mm8

feat: Add preserveAsciiControlCharacters to CsvOptions

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryRequestInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Currently, if a jobID object is passed to the query method, it goes through the slow query path always. This PR allows user to set the location and project ID of the job being created with the JobID object AND take the fast query path if all the conditions for fast query path are met.
Note: If the user specifies the job id string in the job id object being supplied to the query method, the workflow will default to the slow query path and use the job id specified.

feat: add fast query path support when empty jobId object is passed

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FormatOptionsTest.java

feat: add ICEBERG format options

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/HivePartitioningOptions.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/HivePartitioningOptionsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

- [ v] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ v] Ensure the tests and linter pass
- [ v] Code coverage does not decrease (if any source code was changed)
- [v ] Appropriate docs were updated (if necessary)
Fixes #2677 ☕️

feat: add  field in HivePartitioningOptions

---

.kokoro/continuous/graalvm-native-17.cfg
.kokoro/continuous/graalvm-native.cfg

Native Image checks run as continuous jobs in bigquery.

chore(deps): update ghcr.io/graalvm/graalvm-ce docker tag to v22.3.2

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java

fix: custom host  for resumable uploads

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: Partial Projection of Table Metadata

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: Add missing storage related fields to Table, TableInfo and StandardTableDefinition

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/IndexUnusedReason.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/SearchStats.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add support for Search statistics

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/SearchStats.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

fix: SearchStats IndexUnusedReasons null bug

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Add support for converting BigQuery interval type to threeten PeriodDuration, information about the canonical interval form can be found [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#canonical_format_3). Parsing logic was referenced from [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/interval_functions#extract).
Fixes #1849 ☕️

feat: add support for converting interval fields to threeten PeriodDuration

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Dataset.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DatasetInfo.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalDatasetReference.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalDatasetReferenceTest.java
pom.xml

API: https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#externaldatasetreference

feat: add support for ExternalDatasetReference

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java

- [ x ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x ] Ensure the tests and linter pass
- [ x] Code coverage does not decrease (if any source code was changed)
- [ x ] Appropriate docs were updated (if necessary)
Fixes #2830 ☕️

feat: Add support for FileSetSpec

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryOptions.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryRequestInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

Enables preview query features, which currently only includes stateless queries (queries without jobId). These features won't always be enabled on the service side and there are additional checks and conditions.
Fixes https://github.com/googleapis/java-bigquery/issues/2949

feat: add support for preview features

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

- [ x ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ x ] Ensure the tests and linter pass
- [ x ] Code coverage does not decrease (if any source code was changed)
- [ x ] Appropriate docs were updated (if necessary)
Fixes #1742 ☕️

feat: Add InputBytes to extract job statistics

---

README.md
samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java
samples/snippets/src/main/java/com/example/bigquery/TableInsertRowsWithoutRowIds.java
samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsIT.java

Make the example set row id in `addRow`. If row id is missed, it disable the retry b/280865468, which I believe an unexpected behavior to users.
Fixes #3000.

fix: update TableInsertRows.java

---

README.md
google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Routine.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/RoutineInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This also:
- fix an issue where RoutineInfo unit test was being skipped
- fix an issue where ImportLibaries were not being exported in the toPb method
Fixes #3005 ☕️

feat: Add Routine DataGovernanceType

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java

Fix: bigquery.create NullPointerException when job already exists

---

.github/.OwlBot.lock.yaml
.github/workflows/ci.yaml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: Use location in BigQueryOption as the default for query

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR adds the ability to set the universe domain and validate that the parameters are correct prior to each RPC. This is done by calling hasValidUniverseDomain prior to each RPC call in HttpBigQueryRpc. The PR does not change existing functionality of BigQuery and all existing unit and integration tests passes for the default universe domain. Manual testing was performed on a non-default universe domain and we were able to list the test dataset. However, IT will require additional work (as it require additional credential setup) and will be included in a future PR.
Fixes #3088  ☕️

Feat: Add universe domain

---

README.md
google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/EmptyTableResult.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableResult.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/SerializationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableResultTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR adds queryId to TableResult by changing its public constructors. It should be fine to update TableResult constructors to include QueryId since it is used to return results to the user and users should not directly construct TableResult objects.
Fixes #3105 ☕️

Feat: Add queryId to TableResult

---

google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR updates the universe domain except error code/message to be consistent with the error message used in GAPIC. Specifically, with the error code 401 and the message "The configured universe domain (googleapis.com) does not match the universe domain found in the credentials (foo.com). If you haven't configured the universe domain explicitly, googleapis.com is the default."
Fixes #3112

Feat: Update universe domain exception error code/message

---

README.md
google-cloud-bigquery-bom/pom.xml
pom.xml

The BOM declares the published artifacts from this repository. (Historically, this repository has only published one artifact and thus maintainers haven't had a need of creating a BOM.)

chore: adding google-cloud-bigquery-bom

---

.kokoro/continuous/graalvm-native-17.cfg
.kokoro/continuous/graalvm-native.cfg
.kokoro/presubmit/graalvm-native-17.cfg
.kokoro/presubmit/graalvm-native.cfg
owlbot.py
pom.xml
renovate.json

Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central.
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290

chore: use sdk-platform-java-config to consolidate build configs

---

.github/.OwlBot.lock.yaml
README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/MetadataCacheStats.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableMetadataCacheUsage.java
google-cloud-bigquery/src/test/java/MetadataCacheStatsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableMetadataCacheUsageTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Note: This only includes IT test for when the external table does not have metadata cache enabled. Since we are moving away from the GCP java-docs-samples-testing, the IT for when metadata cache enabled with be added after the migration due to the need to create BigLake table with external connection.
Fixes #3134 ☕️

feat: add MetadataCacheStatistics to Job QueryStatistics

---

pom.xml

The Google Cloud share dependencies BOM now declares the Apache
Arrow versions. Therefore, no need to maintain the Apache Arrow
versions in java-bigquery repository.

chore: stop declaring Apache Arrow deps in dependencyManagement

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobStatisticsTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Specifically, [copiedRows, copiedLogicalBytes] are added to CopyStatistics.
Fixes #3206  ☕️

feat: Add new fields to copy job statistics

---

README.md
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Test involves working with a source table and a job that uses the table as an input.  Reorders the cleanup until after the job is complete to avoid possible racing with deletion before completion.
Fixes: https://github.com/googleapis/java-bigquery/issues/3212

testing: reorder test to avoid racing

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Another case of deleting resource before job may be done using it.
Fixes: https://github.com/googleapis/java-bigquery/issues/3208

testing: address another possible test flake

---

.github/workflows/scorecard.yml
benchmark/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldElementType.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Range.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldElementTypeTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RangeTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR also adds the ability to use Range query parameter
Fixes #3235 ☕️

feat: Add Range object to allow reading range value

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Range.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RangeTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: Add support for inserting Range values

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpcTest.java

Fix BigQuery#listDatasets to include dataset location in the response

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableResult.java

Since users depends on TableResult in testing, removing @InternalApi forces maintainers to change/roll out changes to TableResult more carefully in the future.
Fixes #3215 ☕️

fix: Remove @InternalApi from TableResult

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionSettings.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ReadClientConnectionConfiguration.java

This fixes errors in the latest versions of AutoValue
```
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionSettings.java:225: error: [AutoValueBuilderSetterNullable] Setter methods always return the Builder so @Nullable is not appropriate
public abstract Builder setUseReadAPI(Boolean useReadAPI);
^
```
Fixes #3221 ☕️

Fix: @Nullable annotations on builder methods

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldValueTest.java

feat: Add getStringOrDefault method to FieldValue

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java

Bug fix for NPE
NPE is...
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```
From my stacktrace...
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1808)
at java.base/java.util.regex.Matcher.reset(Matcher.java:461)
at java.base/java.util.regex.Matcher.(Matcher.java:256)
at java.base/java.util.regex.Pattern.matcher(Pattern.java:1180)
at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:436)
at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:363)
```
Looks like a bad null check to me

fix: Fixing NPE bug by adding to if clause

---

README.md
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add MetadataCacheMode to ExternalTableDefinition

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

feat: add columnNameCharacterMap to LoadJobConfiguration

---

README.md
samples/snippets/pom.xml

Manually update samples com.google.cloud:libraries-bom to v26.43.0 until renovatebot issue can be resolved.

chore(deps): update dependency com.google.cloud:libraries-bom to v26.43.0

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ConnectionImplTest.java

fix: NPE for executeSelect nonFast path with empty result

---

google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

Use priority instead of job timeout to force non-fast query in executeSelect.
Fixes #3471 ☕️

test: fix flaky IT testExecuteSelectWithCredentials

---

samples/snippets/src/main/java/com/example/bigquery/SimpleApp.java
samples/snippets/src/test/java/com/example/bigquery/SimpleAppIT.java

When running in Google Cloud console, the default google cloud project might not be set leading to 404 errors. This update requires the reader to explicitly set the project value.
This also removes the explicit use of UUID to set jobId as the library now internally generates the value.

docs: Update SimpleApp to explicitly set project id

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadConfiguration.java

fix: Update experimental methods documentation to @internalapi

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java

docs: fix BigQuery documentation formating

---

google-cloud-bigquery/pom.xml
google-cloud-bigquery/src/benchmark/java/com/google/cloud/bigquery/benchmark/Benchmark.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryAlgorithm.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelper.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryParameterValueTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelperTest.java

This PR introduces `java.time` alternatives to existing `org.threeten.bp.*` methods, as well as switching internal variables (if any) to `java.time`
The main constraint is to keep the changes backwards compatible, so for each existing threeten method "`method1(org.threeten.bp.Duration)`" we will add an alternative with a _Duration_ (or _Timestamp_ when applicable) suffix: "`method1Duration(java.time.Duration)`".
For most cases, the implementation will be held in the `java.time` method and the old threeten method will just delegate the call to it. However, for the case of abstract classes, the implementation will be kept in the threeten method to avoid breaking changes (i.e. users that already overloaded the method in their user code).

feat: introduce `java.time` methods and variables

---

benchmark/src/main/java/com.google.cloud.bigquery/ConnImplBenchmark.java

I'm trying to use the `executeSelect` API and faced extremely slow reading.
I tried to use `ConnImplBenchmark` but noticed that the Shema was changed, and the test didn't work.
`bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2017`
Summary of Changes
Added Fields: airport_fee, data_file_year, data_file_month.
Removed Fields: dropoff_longitude, dropoff_latitude, pickup_longitude, pickup_latitude.
After fixing the test I can confirm that we have similar speed results for our use cases.
Reading 100_000 rows takes ~15-20 seconds, which is extremely slow.
```
Running
ROW 100000 Time: 14978 ms
ROW 200000 Time: 16409 ms
ROW 300000 Time: 16966 ms
ROW 400000 Time: 15963 ms
ROW 500000 Time: 17480 ms
```
I'm not sure if there was any performance degradation recently since I can't find any …

fix(test): Update schema for broken ConnImplBenchmark test

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java

The current input parameter for [timestamp()](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java#L304) is unclear regarding the expected format. This PR adds context to the javadocs for the function.
Fixes #2709

docs(bigquery): Add javadoc description of timestamp() parameter.

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/AclTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR enables the use of IAM conditions when accessing a dataset through the create, update, and get API endpoints. The following changes are necessary:
- Add in a new `Expr` type in the `Acl` class for expressing the access conditions
- Create a new `DatasetOption` field to set the access policy version
- Set the access policy version before sending the rpc to the backend when applicable
Buganizer link: b/374156746

feat(bigquery): support IAM conditions in datasets in Java client.

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Connection.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ConnectionImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: NPE when reading BigQueryResultSet from empty tables

---

benchmark/src/main/java/com.google.cloud.bigquery/ConnImplBenchmark.java

Fixes https://github.com/googleapis/java-bigquerystorage/issues/2764
Related issue: https://github.com/googleapis/java-bigquery/pull/3574
SDK still uses the old API and just skips ReadAPI, even if it's enabled.
This happens because of this check: https://github.com/googleapis/java-bigquery/blob/08c483cb726bb36951680687260dd2d0371a9dc0/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java#L1201
In order to use ReadAPI, we need to add any of these configurations, for example, setJobTimeoutMs.
After this, we will see `Not Using Fast Query Path, using jobs.insert` and `Using BigQuery Read API` instead of `Using Fast Query Path`.
After enabling ReadAPI we've got 6-10x speed improvement:
```
Benchmark                                     (rowLimit)  Mode  Cnt …
```

fix(test): Force usage of ReadAPI

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java

Shutdown bqReadClient after arrow stream is processed in highThroughputRead to free up resources
Fixes https://github.com/googleapis/java-bigquery/issues/3571

fix: Close bq read client

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Dataset.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DatasetInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetInfoTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This change implements the resource tag feature from bigquery in the java client library. See doc [here](https://docs.google.com/document/d/1NWeFYxTV_kjlVaLdwbV0OVOOX-kfKa3aUtgEyq3bAb8/edit?tab=t.0#heading=h.kpi8g41cg5iw)
Integration tests for this change can be found at this [PR draft](https://github.com/googleapis/java-bigquery/pull/3652). These tests fail in the kokoro environment because we are not able to able to add [tags](https://pantheon.corp.google.com/iam-admin/tags?inv=1&invt=Abn_Ng&project=cloud-devrel-kokoro-resources&supportedpurview=organizationId) to the project due to lack of permissions. The integration tests pass in my personal cloud project as I have permissions to create and edit [tags](https://pantheon.corp.google.com/iam-admin/tags?inv=1&invt=Abn_Ng&project=liamhuffm …

feat(bigquery): Support resource tags for datasets in java client

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryResultImplTest.java

- Implement wasNull as defined by java.sql.ResultSet for BigQueryResultSet.
- Add a new unittest file for BigQueryResultSet
- Add unittest for BigQueryResultSet getters for both FieldValue type buffer and read API type buffer
- Perform minor refactoring in BigQueryResultSet
Fixes #3648 ☕️

feat: implement wasNull for BigQueryResultSet

---

CONTRIBUTING.md

docs: update CONTRIBUTING.md for users without branch permissions

---

.github/workflows/scorecard.yml
benchmark/pom.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultImpl.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryResultImplTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
pom.xml

feat(bigquery): Implement getArray in BigQueryResultImpl

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java

- [x ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
Fixes #3735  ☕️

fix: Add labels to converter for listTables method (#3735)

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobInfo.java

For existing tables, WRITE_TRUNCATE_DATA preserves schema/constraints and replaces data.
internal issue: b/406848221

feat: add WRITE_TRUNCATE_DATA as an enum value for write disposition

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/CopyJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExtractJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/QueryRequestInfoTest.java

This PR adds support to assign the reservation field in JobConfiguration when creating a job. This field is also propagated to QueryRequestInfo.

feat(bigquery): Add support for reservation field in jobs.

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableResult.java

After some investigation into [Issue #3776](https://github.com/googleapis/java-bigquery/issues/3776), we noticed that getTotalRows() would return 1 for queries that didn't actually return any rows. This docstring explains why the method can potentially return a non-zero value for queries that don't return any rows, such as INSERT, UPDATE, and DELETE.
The reason for this is that the totalRows value can be set to the [numDmlAffectedRows](https://github.com/googleapis/java-bigquery/blob/d6e52e9221a48a374e59e65e46ff230f1424d218/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L1470) in some cases.

docs(bigquery): Update TableResult.getTotalRows() docstring

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryOptions.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryJobConfiguration.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryRequestInfo.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
samples/snippets/src/main/java/com/example/bigquery/QueryJobOptional.java
samples/snippets/src/main/java/com/example/bigquery/QueryShortMode.java
samples/snippets/src/test/java/com/example/bigquery/QueryJobOptionalIT.java

Previously, the QUERY_PREVIEW_ENABLED environmental variable controlled whether or not the client could execute queries without creating a job. This PR removes the environment variable and instead adds a field to BigQueryOptions to control this behavior.
QUERY_PREVIEW_ENABLED is no longer used and has no effect.

feat(bigquery): job creation mode GA

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

This PR adds the options dataset_view and update_mode to the get and patch dataset requests respectively. These new options decide whether the metadata and or ACL information should be checked when retrieving or updating a dataset.

feat(bigquery): Support Fine Grained ACLs for Datasets

---

google-cloud-bigquery/pom.xml

The reason for the rollback is that io-netty version v4.2.1.Final had conflicts with the dep apache.arrow

deps: rollback netty.version to v4.1.119.Final

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryRetryHelper.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableDataWriteChannel.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

The more here refers to `TableDataWriteChannel`. This PR also changes the signature of `BigQueryRetryHelper.runWithRetries()` to include a `boolean` and Otel `Tracer` as parameters.

feat(bigquery): Integrate Otel into retries, jobs, and more

---

google-cloud-bigquery/clirr-ignored-differences.xml
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java

This PR adds support for custom timezones, timestamps, datetimes, null markers, and CSV column matching in both the external tables and load job configurations.
Internal issue: b/374142084

feat(bigquery): Add support for custom timezones and timestamps

---

google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadJobConfiguration.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/LoadJobConfigurationTest.java
google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java

fix: load jobs preserve ascii control characters configuration
