- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
> bug: adding getProjectId() when datasetInfo projectId is null

- samples/pom.xml
> update dependencies and fix parent path

- samples/pom.xml
> feat: skip release/staging for sample artifacts

- .gitignore
> chore: ignore Eclipse and Mac metafiles

- README.md
> docs: update libraries-bom version

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatistics.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/JobStatus.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableDefinition.java
- samples/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
> chore: fix assorted warnings

- .kokoro/run_samples_tests.sh
- samples/src/main/java/com/example/bigquery/CopyMultipleTables.java
- samples/src/test/java/com/example/bigquery/CopyMultipleTablesIT.java
> feat: new sample - Tables: Copy multiple tables

- samples/src/main/java/com/example/bigquery/DeleteTable.java
- samples/src/test/java/com/example/bigquery/DeleteTableIT.java
Fixes b/147376757
This is used for cleaning up tests that require the creation of tables
> feat: new sample - Tables: Delete table

- samples/src/main/java/com/example/bigquery/LoadParquet.java
- samples/src/main/java/com/example/bigquery/QueryWithNamedParameters.java
- samples/src/test/java/com/example/bigquery/QueryWithNamedParametersIT.java
> feat: sample - query with named params

- samples/src/main/java/com/example/bigquery/QueryWithPositionalParameters.java
- samples/src/test/java/com/example/bigquery/QueryWithPositionalParametersIT.java
> feat: sample - query with positional params

- samples/src/main/java/com/example/bigquery/CreatePartitionedTable.java
- samples/src/test/java/com/example/bigquery/CreatePartitionedTableIT.java
> feat: new sample - Table: Column Based Time Partitioning

- samples/src/main/java/com/example/bigquery/CreateClusteredTable.java
- samples/src/test/java/com/example/bigquery/CreateClusteredTableIT.java
> feat: add new sample - Table: Create clustered table

- samples/src/main/java/com/example/bigquery/CreatePartitionedTable.java
- samples/src/main/java/com/example/bigquery/QueryClusteredTable.java
- samples/src/test/java/com/example/bigquery/QueryClusteredTableIT.java
> feat: new sample - Query: Clustered Table

- samples/src/main/java/com/example/bigquery/CreatePartitionedTable.java
- samples/src/main/java/com/example/bigquery/LoadPartitionedTable.java
- samples/src/test/java/com/example/bigquery/LoadPartitionedTableIT.java
> feat: add new sample - Load: Column Based Time Partitioning

- samples/src/test/java/com/example/bigquery/LoadPartitionedTableIT.java
fixes build issues with https://github.com/googleapis/java-bigquery/pull/115
> chore: fix build error

- samples/src/main/java/com/example/bigquery/ListDatasets.java
- samples/src/main/java/com/example/bigquery/ListModels.java
- samples/src/test/java/com/example/bigquery/ListDatasetsIT.java
- samples/src/test/java/com/example/bigquery/ListModelsIT.java
> feat: new sample - Models: List model resources contained in a dataset

- pom.xml
Reference from this [PR](https://github.com/googleapis/java-firestore/pull/53) 
- Error:java: java.lang.NoClassDefFoundError: com/google/auto/service/AutoService
com.google.auto.service.AutoService
> build: update annotationprocessorpaths to include auto-service-annotation.

- samples/src/main/java/com/example/bigquery/CreateDataset.java
add missing underscore in region tag
> sample: fix region tag

- samples/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
- samples/src/main/java/com/example/bigquery/RelaxTableQuery.java
correct region tag for sample https://devrel.corp.google.com/samples/211?product_id=217&priority=P1
> sample: update region tag

- samples/src/main/java/com/example/bigquery/ListTables.java
- samples/src/test/java/com/example/bigquery/ListTablesIT.java
> samples: listTables

- samples/src/main/java/com/example/bigquery/GetTable.java
- samples/src/test/java/com/example/bigquery/GetTableIT.java
> samples: getTable

- samples/src/main/java/com/example/bigquery/UpdateTableExpiration.java
- samples/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java
> samples: update table expiration

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/InsertAllRequest.java
migrate PR #6216 from google-cloud-java
> doc: clarify docs for sending data via streaming inserts

- samples/src/main/java/com/example/bigquery/TableInsertRows.java
- samples/src/test/java/com/example/bigquery/TableInsertRowsIT.java
> samples: add new sample bigquery_table_insert_rows

- samples/src/main/java/com/example/bigquery/AuthSnippets.java
- samples/src/main/java/com/example/bigquery/DeleteDataset.java
> samples: setProjectId explicitly in sample

- samples/src/main/java/com/example/bigquery/AuthDriveScope.java
- samples/src/test/java/com/example/bigquery/AuthDriveScopeIT.java
> samples: new sample bigquery_auth_drive_scope

- samples/src/main/java/com/example/bigquery/NestedRepeatedSchema.java
- samples/src/test/java/com/example/bigquery/NestedRepeatedSchemaIT.java
> samples: new sample bigquery_nested_repeated_schema

- samples/snippets/pom.xml
> samples: add region tag back

- samples/snippets/src/main/java/com/example/bigquery/UpdateTableDescription.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateTableDescriptionIT.java
> docs(samples): Added UpdateTableDescription example.

- google-cloud-bigquery/pom.xml
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardTableDefinition.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/StandardTableDefinitionTest.java
> chore: remove hamcrest dependency and modify test case

- google-cloud-bigquery/pom.xml
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryExceptionTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryOptionsTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/DatasetTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/JobTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ModelTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/RoutineTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableDataWriteChannelTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/testing/RemoteBigQueryHelperTest.java
- pom.xml
> chore: add mockitto dependency and convert test cases

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java
> fix: error message for get routine

- google-cloud-bigquery/pom.xml
- pom.xml
> deps: restrict -annotation deps

- samples/snippets/src/main/java/com/example/bigquery/SimpleQuery.java
- samples/snippets/src/test/java/com/example/bigquery/SimpleQueryIT.java
> docs(samples): adding simple query example for completeness

- samples/snippets/src/main/java/com/example/bigquery/SaveQueryToTable.java
- samples/snippets/src/test/java/com/example/bigquery/SaveQueryToTableIT.java
> docs(samples): adding destination query sample and test

- samples/snippets/src/main/java/com/example/bigquery/Query.java
- samples/snippets/src/test/java/com/example/bigquery/QueryIT.java
> docs(samples): add query

- samples/snippets/src/main/java/com/example/bigquery/CreateModel.java
- samples/snippets/src/main/java/com/example/bigquery/DeleteModel.java
- samples/snippets/src/test/java/com/example/bigquery/CreateModelIT.java
- samples/snippets/src/test/java/com/example/bigquery/DeleteModelIT.java
> docs(samples): add create and delete model

- samples/snippets/src/test/java/com/example/bigquery/GetModelIT.java
> refactor(samples): get model

- samples/snippets/src/test/java/com/example/bigquery/ListModelsIT.java
> refactor(samples): listmodels

- samples/snippets/src/main/java/com/example/bigquery/QueryBatch.java
- samples/snippets/src/test/java/com/example/bigquery/QueryBatchIT.java
> docs(samples): add query batch

- samples/snippets/src/main/java/com/example/bigquery/CancelJob.java
- samples/snippets/src/test/java/com/example/bigquery/CancelJobIT.java
> docs(samples): add cancel job

- samples/snippets/src/main/java/com/example/bigquery/CreateTableWithoutSchema.java
- samples/snippets/src/test/java/com/example/bigquery/CreateTableWithoutSchemaIT.java
> docs(samples): add create table without schema

- samples/snippets/src/main/java/com/example/bigquery/DatasetExists.java
- samples/snippets/src/test/java/com/example/bigquery/DatasetExistsIT.java
> docs(samples): add dataset exists

- samples/snippets/src/main/java/com/example/bigquery/CreateRoutine.java
- samples/snippets/src/main/java/com/example/bigquery/DeleteRoutine.java
- samples/snippets/src/test/java/com/example/bigquery/CreateRoutineIT.java
- samples/snippets/src/test/java/com/example/bigquery/DeleteRoutineIT.java
> docs(samples): add create and delete routine

- samples/snippets/src/main/java/com/example/bigquery/CreateRoutineDDL.java
- samples/snippets/src/test/java/com/example/bigquery/CreateRoutineDDLIT.java
> docs(samples): add create routine ddl

- samples/snippets/src/test/java/com/example/bigquery/AddEmptyColumnIT.java
> refactor: fix imports order and run code formatter

- samples/snippets/src/main/java/com/example/bigquery/CreateView.java
- samples/snippets/src/test/java/com/example/bigquery/CreateViewIT.java
> docs(samples): add create view

- samples/snippets/src/main/java/com/example/bigquery/GetRoutine.java
- samples/snippets/src/test/java/com/example/bigquery/GetRoutineIT.java
> docs(samples): add get routine

- samples/snippets/src/main/java/com/example/bigquery/GetView.java
- samples/snippets/src/test/java/com/example/bigquery/GetViewIT.java
> docs(samples): add get view

- samples/snippets/src/main/java/com/example/bigquery/CreateTableCMEK.java
- samples/snippets/src/test/java/com/example/bigquery/CreateTableCMEKIT.java
> docs(samples): add create cmek table

- samples/snippets/src/main/java/com/example/bigquery/CopyTableCMEK.java
- samples/snippets/src/test/java/com/example/bigquery/CopyTableCMEKIT.java
> docs(samples): add copy cmek table

- samples/snippets/src/main/java/com/example/bigquery/DeleteLabelDataset.java
- samples/snippets/src/test/java/com/example/bigquery/DeleteLabelDatasetIT.java
> docs(samples): add delete label on a dataset

- samples/snippets/src/main/java/com/example/bigquery/DeleteLabelTable.java
- samples/snippets/src/test/java/com/example/bigquery/DeleteLabelTableIT.java
> docs(samples): add delete label on a table

- samples/snippets/src/main/java/com/example/bigquery/CreatePartitionedTable.java
- samples/snippets/src/test/java/com/example/bigquery/CreatePartitionedTableIT.java
> refactor(samples): create a partition table

- samples/snippets/src/main/java/com/example/bigquery/LabelDataset.java
- samples/snippets/src/test/java/com/example/bigquery/LabelDatasetIT.java
> docs(samples): add label dataset

- samples/snippets/src/main/java/com/example/bigquery/LabelTable.java
- samples/snippets/src/test/java/com/example/bigquery/LabelTableIT.java
> docs(samples): add label table

- samples/snippets/src/test/java/com/example/bigquery/DeleteLabelDatasetIT.java
> refactor(samples): delete a label on a dataset

- samples/snippets/src/test/java/com/example/bigquery/DeleteLabelTableIT.java
> refactor(samples): delete a label on a table

- samples/snippets/src/main/java/com/example/bigquery/ExtractTableCompressed.java
- samples/snippets/src/test/java/com/example/bigquery/ExtractTableCompressedIT.java
> docs(samples): add extract compressed table

- samples/snippets/src/main/java/com/example/bigquery/GetDatasetLabels.java
- samples/snippets/src/test/java/com/example/bigquery/GetDatasetLabelsIT.java
> docs(samples): add get dataset labels

- samples/snippets/src/main/java/com/example/bigquery/GetTableLabels.java
- samples/snippets/src/test/java/com/example/bigquery/GetTableLabelsIT.java
> docs(samples): add get table labels

- samples/snippets/src/main/java/com/example/bigquery/DeleteLabelTable.java
> fix(sample): region tag

- samples/snippets/src/main/java/com/example/bigquery/ListRoutines.java
- samples/snippets/src/test/java/com/example/bigquery/ListRoutinesIT.java
> docs(samples): add list routines

- samples/snippets/src/main/java/com/example/bigquery/ListDatasetsByLabel.java
- samples/snippets/src/test/java/com/example/bigquery/ListDatasetsByLabelIT.java
> docs(samples): add list dataset by label

- samples/snippets/src/main/java/com/example/bigquery/ListJobs.java
- samples/snippets/src/test/java/com/example/bigquery/ListJobsIT.java
> docs(samples): add list jobs

- samples/snippets/src/main/java/com/example/bigquery/GrantViewAccess.java
- samples/snippets/src/test/java/com/example/bigquery/GrantViewAccessIT.java
> docs(samples): add grant view access

- samples/snippets/src/main/java/com/example/bigquery/LoadAvroFromGCS.java
- samples/snippets/src/test/java/com/example/bigquery/LoadAvroFromGCSIT.java
> docs(samples): add load table from gcs using avro file

- samples/snippets/src/main/java/com/example/bigquery/LoadJsonFromGCSAutodetect.java
- samples/snippets/src/test/java/com/example/bigquery/LoadJsonFromGCSAutodetectIT.java
> docs(samples): add load json file from gcs into a table with autodetect schema

- samples/snippets/pom.xml
> chore: fix tag

- samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java
- samples/snippets/src/test/java/com/example/bigquery/TableInsertRowsIT.java
> refactor(samples): insert rows into a table

- samples/snippets/src/main/java/com/example/bigquery/LoadJsonFromGCSCMEK.java
- samples/snippets/src/test/java/com/example/bigquery/LoadJsonFromGCSCMEKIT.java
> docs(samples): add load json table with encryption key from gcs

- samples/snippets/src/main/java/com/example/bigquery/QueryDestinationTableCMEK.java
- samples/snippets/src/test/java/com/example/bigquery/QueryDestinationTableCMEKIT.java
> docs(samples): add query destination table with encryption key

- samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGcs.java
- samples/snippets/src/test/java/com/example/bigquery/LoadCsvFromGcsIT.java
> refactor(samples): load csv table from gcs

- samples/snippets/src/main/java/com/example/bigquery/LoadOrcFromGCS.java
- samples/snippets/src/test/java/com/example/bigquery/LoadOrcFromGCSIT.java
> docs(samples): load orc file into a table from gcs

- samples/snippets/src/main/java/com/example/bigquery/LoadJsonFromGCSTruncate.java
- samples/snippets/src/test/java/com/example/bigquery/LoadJsonFromGCSTruncateIT.java
> docs(samples): add load json table with overwrite data from gcs

- samples/snippets/src/main/java/com/example/bigquery/LoadOrcFromGcsTruncate.java
- samples/snippets/src/test/java/com/example/bigquery/LoadOrcFromGcsTruncateIT.java
> docs(samples): add load orc file and overwrite data into a table from gcs

- samples/snippets/src/main/java/com/example/bigquery/QueryDryRun.java
- samples/snippets/src/test/java/com/example/bigquery/QueryDryRunIT.java
> docs(samples): add query dry run

- samples/snippets/src/main/java/com/example/bigquery/QueryExternalGCSPerm.java
- samples/snippets/src/test/java/com/example/bigquery/QueryExternalGCSPermIT.java
> docs(samples): add query on external table from gcs

- samples/snippets/src/main/java/com/example/bigquery/QueryDisableCache.java
- samples/snippets/src/test/java/com/example/bigquery/QueryDisableCacheIT.java
> docs(samples): add query disable cache

- samples/snippets/src/main/java/com/example/bigquery/QueryExternalGCSTemp.java
- samples/snippets/src/test/java/com/example/bigquery/QueryExternalGCSTempIT.java
> docs(samples): add query on external temp table from gcs

- samples/snippets/src/main/java/com/example/bigquery/QueryLargeResults.java
- samples/snippets/src/test/java/com/example/bigquery/QueryLargeResultsIT.java
> docs(samples): add query legacy large results

- samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java
- samples/snippets/src/test/java/com/example/bigquery/QueryPaginationIT.java
> docs(samples): add query pagination

- samples/snippets/src/main/java/com/example/bigquery/QueryPartitionedTable.java
- samples/snippets/src/test/java/com/example/bigquery/QueryPartitionedTableIT.java
> docs(samples): add query partitioned table

- samples/snippets/src/main/java/com/example/bigquery/QueryWithArrayParameters.java
- samples/snippets/src/test/java/com/example/bigquery/QueryWithArrayParametersIT.java
> docs(samples): add query with arrays parameters

- samples/snippets/src/main/java/com/example/bigquery/QueryWithTimestampParameters.java
- samples/snippets/src/test/java/com/example/bigquery/QueryWithTimestampParametersIT.java
> docs(samples): add query with timestamp parameters

- samples/snippets/src/main/java/com/example/bigquery/QueryScript.java
- samples/snippets/src/test/java/com/example/bigquery/QueryScriptIT.java
> docs(samples): add query script

- samples/snippets/src/main/java/com/example/bigquery/QueryTotalRows.java
- samples/snippets/src/test/java/com/example/bigquery/QueryTotalRowsIT.java
> docs(samples): add query total rows

- samples/snippets/src/main/java/com/example/bigquery/TableExists.java
- samples/snippets/src/test/java/com/example/bigquery/TableExistsIT.java
> docs(samples): add table exists

- samples/snippets/src/main/java/com/example/bigquery/UpdateDatasetPartitionExpiration.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateDatasetPartitionExpirationIT.java
> docs(samples): add update dataset partition expiration

- samples/snippets/src/main/java/com/example/bigquery/UndeleteTable.java
- samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
> docs(samples): add undelete table

- samples/snippets/src/main/java/com/example/bigquery/UpdateModelDescription.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateModelDescriptionIT.java
> docs(samples): add update model description

- samples/snippets/src/main/java/com/example/bigquery/UpdateTableCMEK.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateTableCMEKIT.java
> docs(samples): add update table cmek

- samples/snippets/src/main/java/com/example/bigquery/LoadTableClustered.java
- samples/snippets/src/test/java/com/example/bigquery/LoadTableClusteredIT.java
> refactor(samples): load clustered table

- samples/snippets/src/main/java/com/example/bigquery/UpdateRoutine.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateRoutineIT.java
> docs(samples): add update routine

- samples/snippets/src/test/java/com/example/bigquery/UpdateTableRequirePartitionFilter.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateTableRequirePartitionFilterIT.java
> docs(samples): add update table require partition filter

- samples/snippets/src/main/java/com/example/bigquery/UpdateViewQuery.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateViewQueryIT.java
> docs(samples): update view query

- samples/snippets/src/main/java/com/example/bigquery/DeleteDatasetAndContents.java
- samples/snippets/src/test/java/com/example/bigquery/DeleteDatasetAndContentsIT.java
> docs(samples): add delete dataset and contents

- samples/snippets/src/main/java/com/example/bigquery/QueryWithNamedTypesParameters.java
- samples/snippets/src/test/java/com/example/bigquery/QueryWithNamedTypesParametersIT.java
> docs(samples): add query with name types parameters

- samples/snippets/src/main/java/com/example/bigquery/AuthorizedViewTutorial.java
- samples/snippets/src/test/java/com/example/bigquery/AuthorizedViewTutorialIT.java
> docs(samples): add authorized view tutorial

- samples/snippets/src/main/java/com/example/bigquery/AddColumnLoadAppend.java
- samples/snippets/src/test/java/com/example/bigquery/AddColumnLoadAppendIT.java
> refactor(samples): add column load append

- samples/snippets/src/main/java/com/example/bigquery/LoadCsvFromGCSAutodetect.java
- samples/snippets/src/test/java/com/example/bigquery/LoadCsvFromGCSAutodetectIT.java
> docs(samples): add load csv autodetect data from gcs

- samples/snippets/src/main/java/com/example/bigquery/QueryExternalSheetsTemp.java
- samples/snippets/src/test/java/com/example/bigquery/QueryExternalSheetsTempIT.java
> docs(samples): add query external sheet temp table

- samples/snippets/src/main/java/com/example/bigquery/QueryExternalSheetsPerm.java
- samples/snippets/src/test/java/com/example/bigquery/QueryExternalSheetsPermIT.java
> docs(samples): add query external sheet permanent table

- benchmark/README.md
- benchmark/pom.xml
- benchmark/src/main/java/com.google.cloud.bigquery/QueryBenchmark.java
- pom.xml
> feat: add jmh benchmark module

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
> fix: npe for destination table

- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> test: fix flaky test

- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> test: fix build

- .github/sync-repo-settings.yaml
in order to grant correct access to CODEOWNERS of this repo
> chore: add sync-repo-settings.yaml to grant correct access

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java
> fix: nullpointer exception when executionerror is null

- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> test: fix testCancelJob failed

- pom.xml
> chore: add version property tag

- .kokoro/nightly/samples.cfg
- .kokoro/run_samples_resource_cleanup.sh
- samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
- synth.py
> ci(samples): add nightly resource cleanup

- samples/snippets/src/main/java/com/example/bigquery/ResourceCleanUp.java
since it is returning null
will investigate this issue #848
> ci(chore): comment out dataset.getCreationTime method

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
> refactor: remove duplicate page token field from listdatasets

- .kokoro/nightly/samples.cfg
- .kokoro/run_samples_resource_cleanup.sh
```
ERROR: (gcloud.auth.activate-service-account) Unable to read file [/tmpfs/src/gfile/service-acct.json]: [Errno 2] No such file or directory: '/tmpfs/src/gfile/service-acct.json'
```
> ci: nightly cleanup cleanup

- samples/snippets/src/main/java/com/example/bigquery/ExportQueryResultsToS3.java
- samples/snippets/src/main/java/com/example/bigquery/SimpleApp.java
- samples/snippets/src/test/java/com/example/bigquery/SimpleAppIT.java
> refactor(samples): add nested fields

- samples/snippets/src/main/java/com/example/bigquery/UpdateIamPolicy.java
- samples/snippets/src/test/java/com/example/bigquery/UpdateIamPolicyIT.java
> docs(samples): add update iam policy for table

- samples/snippets/src/main/java/com/example/bigquery/DatasetExists.java
> samples: fix sample

- samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java
- samples/snippets/src/test/java/com/example/bigquery/ExtractTableToJsonIT.java
> docs(samples): fix sample issue

- samples/snippets/pom.xml
> chore(ci): xml namespace declaration in samples/snippets/pom.xml

- .github/release-please.yml
- .github/sync-repo-settings.yaml
- synth.py
> build: configure branch 1.127.12-sp as a release branch

- samples/snippets/src/main/java/com/example/bigquery/UpdateTableExpiration.java
> docs(sample): update UpdateTableExpiration sample

- renovate.json
> chore: update dependencyDashboard labels

- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Backend fix is in.
Fixes #1443
> chore(test): add back test condition

- pom.xml
For patching a security vulnerability.
> deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.20.2

- README.md
- samples/snippets/pom.xml
> chore: update README to add missing closing tag

- samples/snippets/src/test/java/com/example/bigquery/UpdateTableExpirationIT.java
> docs(samples): update UpdateTableExpirationIT to fix failing IT.

- README.md
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Acl.java
> fix: add missing equality check for targetTypes in DatasetAclEntity

- README.md
- samples/snippets/src/main/java/com/example/bigquery/AuthorizeDataset.java
- samples/snippets/src/test/java/com/example/bigquery/AuthorizeDatasetIT.java
Added Sample and IT for AuthorizeDataset
> docs(sample): Added AuthorizeDataset Sample

- samples/snippets/src/test/java/com/example/bigquery/UndeleteTableIT.java
Caused by empty table schema
Fixes #1911
> docs(samples): fix undeleteTable sample IT failure

- .kokoro/nightly/integration.cfg
- README.md
- owlbot.py
Reverts googleapis/java-bigquery#1915
Fixes #1898 
Fixes #1899 
Fixes #1900
> Revert "chore: revert nightly integration project"

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 2.10.9

- .kokoro/build.sh
- owlbot.py
> chore: disable graalvm ITs till #2007 is fixed

- benchmark/src/main/java/com.google.cloud.bigquery/ConnImplBenchmark.java
Updated initialisation logic for ConnectionSettings and refactored the code
Fixes #2015☕️
> chore: Benchmark logic update and clean-up

- .kokoro/build.sh
> chore: fix nightly integration test

- samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java
- Updated example to loop through all remaining pages
Changes for the open issue: https://github.com/googleapis/java-bigquery/issues/2073
> docs(samples): update querypagination sample

- pom.xml
Reverts googleapis/java-bigquery#1786
> chore: revert "deps: update dependency org.assertj:assertj-core to v3"

- README.md
- benchmark/src/main/java/com.google.cloud.bigquery/ConnImplBenchmark.java
Added benchmarking logic for bigquery.query
Fixes #2086 ☕️
> chore: Added benchmarking logic for bigquery.query

- .github/sync-repo-settings.yaml
- README.md
> chore: mark native image checks as required

- google-cloud-bigquery/clirr-ignored-differences.xml
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LoadConfiguration.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/WriteChannelConfiguration.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/WriteChannelConfigurationTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Adding getDecimalTargetTypes and getDecimalTargetTypes and modified related unit test cases. 
Fixes internal issue b/234571438
> feat: Add decimal target type

- .kokoro/build.sh
- google-cloud-bigquery/pom.xml
> fix(java): make field accessible to address Java 17 issue with arrow

- .kokoro/build.sh
- .kokoro/nightly/graalvm-native-17.cfg
- .kokoro/nightly/graalvm-native.cfg
- README.md
Follow-up to https://github.com/googleapis/java-bigquery/pull/2165
> ci: run ITNightlyBigqueryTest with native image compilation as nightly job

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITNightlyBigQueryTest.java
Defaulted timeoutMs to 10s & Added additional logging
Fixes #2248 ☕️
> fix: Socket-timeout at bigquery.it.ITNightlyBigQueryTest: testForTableNotFound

- .github/release-please.yml
- .github/sync-repo-settings.yaml
- README.md
> feat: next release from main branch is 2.20.0

- .kokoro/build.sh
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
Fixes #2485
Fixes #2496 
Fixes #2498
Fixes #2497
> chore: fix named query parameter struct tests

- samples/snippets/src/main/java/com/example/bigquery/CreateDatasetAws.java
related: internal issue 270264394
> docs: remove stale snippet comment

- README.md
- samples/snippets/src/main/java/com/example/bigquery/CreateDatasetWithRegionalEndpoint.java
- samples/snippets/src/test/java/com/example/bigquery/CreateDatasetWithRegionalEndpointIT.java
> doc: Creating regional dataset sample

- .github/workflows/scorecard.yml
> chore: Create scorecard.yaml

- samples/snippets/src/main/java/com/example/bigquery/QueryWithStructsParameters.java
> fix: QueryWithStructsParameters sample mismatch

- README.md
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/BigQueryRpc.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
-  Didn't open an issue because this seems trivial, happy to adapt if necessary.
- [x ] Ensure the tests and linter pass (mvn test verify
- [x ] Code coverage does not decrease (if any source code was changed)
- [x ] Appropriate docs were updated (if necessary)
> feat: Allow passing autodetect_schema on table update

- README.md
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryOptions.java
> feat: Increase default Read API timeout to 60s

- .gitignore
- README.md
- google-cloud-bigquery/clirr-ignored-differences.xml
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/IndexUnusedReason.java
> fix: hide TableReference data struct

- README.md
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryResultImpl.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> fix: getDouble in read API path

- .kokoro/nightly/integration.cfg
- owlbot.py
> chore: run stateless query IT with allow listed project

- README.md
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Field.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldElementType.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/LegacySQLTypeName.java
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/StandardSQLTypeName.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/FieldElementTypeTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> feat: Support RANGE schema

- google-cloud-bigquery-bom/pom.xml
Follow up to https://github.com/googleapis/java-bigquery/pull/3144
> chore: use sdk-platform-java-config instead of java-shared-config

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> chore: next release from main branch is 2.36.0

- README.md
- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/ExternalTableDefinitionTest.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> feat: Add support for ObjectMetadata

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java
- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
> fix: add clustering value to ListTables result

- google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java
This PR addresses recent flakes observed in two tests.  In the first, we change validation for a DML test to examine DML stats rather then rescanning row data.  In the second, we switch a test query used for faster query to be deterministic, as the suspicion is that stale cached results are impacting assertions about how the query was run.
Fixes: https://github.com/googleapis/java-bigquery/issues/3386
Fixes: https://github.com/googleapis/java-bigquery/issues/3391
> testing: reduce flakiness of tests

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> chore: setup 2.40.x lts branch

- .github/workflows/unmanaged_dependency_check.yaml
- .kokoro/continuous/graalvm-native-17.cfg
- .kokoro/continuous/graalvm-native.cfg
- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
- google-cloud-bigquery-bom/pom.xml
- pom.xml
this combines and should
close #3523 
close #3525
BEGIN_COMMIT_OVERRIDE
chore(deps): update dependency com.google.cloud:google-cloud-bigquerystorage-bom to v3.9.3
deps: update dependency com.google.cloud:sdk-platform-java-config to v3.37.0
END_COMMIT_OVERRIDE
> chore(deps): update dependency sdk-platform-java-config and google-cloud-bigquery-bom

- google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java
> docs: reformat javadoc

- benchmark/pom.xml
> test: fix benchmark test missing maven configuration

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 2.49.0

- renovate.json
> chore: group pull requests from one google-cloud-java release

- CONTRIBUTING.md
> docs: update maven format command

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 2.53.0
